[project]
name = "wishper"
version = "0.1.0"
description = "project"
readme = "README.md"
authors = [
    { name = "Adam", email = "example@mail.com" }
]
requires-python = ">=3.12"
dependencies = [
    
]

[dependency-groups]
dev = [
    
]

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
